import type { Metadata } from "next";
import "./globals.css";
import { Rubik, Londrina_Shadow } from "next/font/google";
import Navbar from "@/components/Navbar";

const londrina = Londrina_Shadow({
  subsets: ["latin"],
  weight: ["400"],
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "IntoxiQuest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${londrina.className}  antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
